### PR TITLE
multiclass classification

### PR DESCRIPTION
**Pull request by alionaBER**
The suggested function trandforms the matrix with predictions into k matrices following a one-vs-all principle. Next, the unsertainty estimation is done for each class separately. In binary classification the estimation happens for y(x)=P(Y=1|X=x). Following this logic, k variance estimations are done, where instances of a particur class is the category of interest (positive class) and all others are negative. 
The output is a dataframe with predited class probabilities and variance estimates for each class.

### CODE REVIEW

**Comment by swager** [comment]
Thanks a lot; this looks like a useful extension. Before merging, could you please add a test for this to the testthat directory?

**Comment by alionaBER** [comment]
Please let me know if you recommend any additional tests.

**Comment by swager** [comment]
Looks good. Also -- and sorry for not bringing this up in my previous comment -- could you please add roxygen-style documentation for the function, like in the other functions in the package? (If you're interested, here's a reference on documentation with roxygen: http://kbroman.org/pkg_primer/pages/docs.html)

**Comment by alionaBER** [comment]
Thank you very much for the feedback and your prompt replies!

**Comment by swager** [comment]
Thanks again!

**Pull request merged**
