### PR TITLE
separate InfJack from randomForestInfJack

### PR DESCRIPTION
**Pull request by zmjones**
this should not change any functionality as you've implemented it but it would allow the estimator to be used with other compatible implementations of RF if they provide the tree prediction and inbag matrices.

i checked your examples and things appear to be working correctly. i can write some unit tests if that is desirable as well.

### CODE REVIEW

**Comment by swager** [comment]
Thanks a lot! This looks like a useful refactor. A few points:
- I think it would be good to keep the "calibration" step inside the new infJack function. Without calibration, the method may produce negative variance estimates that then need to be dealt with ad-hoc. The calibration procedure is not specific to random forests.
- infJack shouldn't need "newdata" as an argument; it should get everything it needs from the "pred" matrix.
- If you could write some unit tests, that would be great.
- For consistency, the method should be infJack instead of InfJack.

**Comment by zmjones** [comment]
ok thanks!

is it alright if i use [testthat](https://github.com/hadley/testthat)?

**Comment by swager** [comment]
testthat sounds great, thanks!

**Comment by zmjones** [comment]
the unit tests are a bit silly but might catch some errors. i made a few changes to some of the variables in the ij and the eb parts of the code that was originally in randomForestInfJack but I think they were all simple things. i looked at the graphs generated from your examples before and after the changes and so no obvious errors. some quick checking would be good though!

i think i incorporated all of your points. additionally i used roxygen2 to generate the namespace and added randomForest and testthat to suggests.

i assumed (due to the documentation) that you planned on exposing the EB functions as well?

cheers

**Comment by swager** [comment]
Thanks again for your work on this!

**Pull request merged**
